Repository owncloud/impersonate, pull requests merged in 2019-02, with the labels that each got.

#134 Add option for all group admins to impersonate their group memebers
  controller/settingscontroller.php
  js/impersonate.js
  js/settings-admin.js
  templates/settings-admin.php
  tests/controller/SettingsControllerTest.php
Labels: 3 - To Review

#140 Add clean-deps to Makefile
  Makefile
Labels: 4 - To release, QA-team

#137 Expose dist through make help
  Makefile
  README.md
Labels: 2 - Developing
