Repository owncloud/impersonate, pull requests merged in 2020-04, with the labels that each got.

#160 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/Util.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#161 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To Review, QA-team

#162 [Tests-Only] Bump phan 2.7 & Run phan in CI
  .drone.star
  .phan/config.php
  appinfo/app.php
  lib/Util.php
  vendor-bin/phan/composer.json
Labels: QA-team

#163 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To Review, QA-team
